pipeline:
  build:
    group: build
    image: plugins/ecr
    repo: 612427630422.dkr.ecr.us-east-1.amazonaws.com/data-platform/superset
    tags:
      - ${DRONE_COMMIT_SHA:0:8}
      - ${DRONE_COMMIT_BRANCH}
      - latest
